shoppapp.webui/Models/CategoryEntity.cs
namespace shoppapp.webui.Models
{
    public class CategoryEntity
    {
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        
    }
}

shoppapp.webui/Models/ProductEntity.cs
using System.ComponentModel.DataAnnotations;

namespace shoppapp.webui.Models
{
    public class ProductEntity
    {
        public int ProductId { get; set; }
        [Required]
        [StringLength(60,MinimumLength=10,ErrorMessage="Ürün ismi 10-60 karakter aralığında olmalıdır.")]
        public string Name { get; set; }
        [Required(ErrorMessage="Fiyat girmelisiniz.")]
        [Range(1,100000)]
        public double? Price { get; set; }
        public string Description { get; set; }
        [Required]
        public string ImageUrl { get; set; }
        public bool IsApproved { get; set; }
        [Required]
        public int? CategoryId { get; set; }
    }
}

shoppapp.webui/ViewModels/ProductViewModel.cs
using System.Collections.Generic;
using shoppapp.webui.Models;
//burada using namespace yok. Virtual class olarak tanımlıyoruz aslında.
public class ProductViewModel
{
    //burada 2 farklı entity'yi paketlemiş olduk 2den fazlası da benzer şekilde paketlenebilir. 
    //Paketleme için 'ViewModel' kullanıyoruz.
    
    public List<ProductEntity> Products { get; set; }
}

shoppapp.webui/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using shoppapp.webui.Data;
using shoppapp.webui.Models;

namespace shoppapp.webui.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var productViewModel = new ProductViewModel()
            {
                Products = ProductRepository.Products
            };
            return View(productViewModel);
        }
        public ActionResult About()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return View("MyView");
        }
    }
}

shoppapp.webui/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using shoppapp.webui.Data;
using shoppapp.webui.Models;


namespace shoppapp.webui.Controllers
{
    public class ProductController : Controller
    {
        public ActionResult Index()
        {
            //View'e veri aktarım yöntemleri
            //ViewBag,Models,ViewData 
            var product = new ProductEntity { Name = "monster", Price = 4300, Description = "Gaming Pc" };           
            ViewBag.Category = "Laptoplar";
            ViewBag.Product = product;


            return View();
        }

        public IActionResult ProductList(int? id, string q)
        {
            var products = ProductRepository.Products;

            if (id != null)
            {
                products = products.Where(p => p.CategoryId == id).ToList();
            }

            if (!string.IsNullOrEmpty(q))
            {
                products = products.Where(a => a.Name.ToLower().Contains(q.ToLower()) || a.Description.ToLower().Contains(q.ToLower())).ToList();
            }

            var productViewModel = new ProductViewModel()
            {
                Products = products
            };

            return View(productViewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(CategoryRepository.Categories, "CategoryId", "Name");
            return View(new ProductEntity());//null almamak için
        }
        [HttpPost]
        public IActionResult Create(ProductEntity p)
        {
            if (ModelState.IsValid)
            {
                ProductRepository.AddProduct(p);
                return RedirectToAction("ProductList");
            }
            ViewBag.Categories = new SelectList(CategoryRepository.Categories, "CategoryId", "Name");
            return View(p);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Categories = new SelectList(CategoryRepository.Categories, "CategoryId", "Name");
            return View(ProductRepository.GetProductById(id));
        }
        [HttpPost]
        public IActionResult Edit(ProductEntity p)
        {
            ProductRepository.EditProduct(p);
            return RedirectToAction("ProductList");
        }
        public IActionResult Detail(int id)
        {
            return View(ProductRepository.GetProductById(id));
        }

        [HttpPost]
        public IActionResult Delete(int ProductId)
        {
            ProductRepository.DeleteProduct(ProductId);
            return RedirectToAction("ProductList");
        }
    }
}

shoppapp.webui/ViewComponents/CategoriesViewComponent.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using shoppapp.webui.Data;
using shoppapp.webui.Models;

namespace shoppapp.webui.ViewComponents
{
    public class CategoriesViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke(){    
            if(RouteData.Values["action"].ToString()=="ProductList") 
                ViewBag.SelectedCategory = RouteData?.Values["id"];
            return View(CategoryRepository.Categories);
        }
    }
}

shoppapp.webui/Views/Home/About.cshtml
@* @{
    ViewData["Title"] = "About";
    Layout = "_Layout";
}  *@
 @section Categories{
        @await Component.InvokeAsync("Categories")
 }
    About

shoppapp.webui/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "List";
}
@* @{
    Layout = "_Layout";
} *@
@model ProductViewModel

@{
    var products = Model.Products;

}
@section MessageBox{
    <div class="alert alert-success text-center m-0">
        Naber bruh?
    </div>
}
 @section Scripts{
     
 }

 @section Header{
     @await Html.PartialAsync("_header")
 }
 
@if (Model.Products.Count == 0)
{
    @await Html.PartialAsync("_noproduct")
}
else
{
    <div class="row">

        @foreach (var item in products)//Model.Products yerine yukarda var tanımladık onu kullandık
        {
            <div class="col-md-3">
                @await Html.PartialAsync("_product",item)
            </div>
        }
    </div>
} 

shoppapp.webui/Views/Home/MyView.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
    <title>Home</title>
</head>

<body>
    @await Html.PartialAsync("_navbar")
    Home/Contact
</body>

</html>

shoppapp.webui/Views/Product/Create.cshtml
@model ProductEntity

<form method="POST">
    @* <div asp-validation-summary="All" class="text-danger"></div> *@
    <div class="form-group">
        <label for="Name">Name</label>
        <input asp-for="Name" value="@Model.Name" class="form-control">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Price">Price</label>
        <input asp-for="Price" value="@Model.Price" class="form-control">
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Description">Description</label>
        <textarea asp-for="Description" value="@Model.Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="ImageUrl">ImageUrl</label>
        <input asp-for="ImageUrl" value="@Model.ImageUrl" class="form-control">
        <span asp-validation-for="ImageUrl" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="CategoryId">CategoryId</label>
        @* <input type="text" name="CategoryId" class="form-control"> *@
        <select asp-for="CategoryId" asp-items="@ViewBag.Categories" class="form-control">
            <option selected disabled>Seçiniz</option>
        </select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

shoppapp.webui/Views/Product/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}

shoppapp.webui/Views/Product/Detail.cshtml
 @model ProductEntity

 @section Categories{
        @await Component.InvokeAsync("Categories")
 }

<div class="card mb-3">
    <div class="card-body">
        <div class="row no-gutters">
            <div class="col-md-3">
                    <img class="card-img" src="~/images/@Model.ImageUrl" alt="">
            </div>
            <div class="col-md-9">
                
                <h5 class="card-title">
                    @Model.Name 
                </h5>
                <div class="p card-text">
                    @Model.Description
                </div>
                <div class="p card-text">
                    <div class="text-muted">
                       @Model.Price
                    </div>
                </div>
                
            </div>
        </div>
    </div>    
</div>

shoppapp.webui/Views/Product/Edit.cshtml
@model ProductEntity

<form method="POST">
    <input type="hidden" name="ProductId" value="@Model.ProductId" >
    <div class="form-group">
        <label for="Name">Name</label>
        <input asp-for="Name" value="@Model.Name" class="form-control">
    </div>
    <div class="form-group">
        <label for="Price">Price</label>
        <input asp-for="Price" value="@Model.Price" class="form-control">
    </div>
    <div class="form-group">
        <label for="Description">Description</label>
        <textarea asp-for="Description" value="@Model.Description" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label for="ImageUrl">ImageUrl</label>
        <input asp-for="ImageUrl" value="@Model.ImageUrl" class="form-control">
    </div>
    <div class="form-group">
        <label for="CategoryId">CategoryId</label>
        <select asp-for="CategoryId" asp-items="@ViewBag.Categories" class="form-control">
            <option selected disabled>Seçiniz</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

shoppapp.webui/Views/Product/Index.cshtml
 @* @{
    Layout = "_Layout";
} *@
 @section Categories{
        @await Component.InvokeAsync("Categories")
 }
    Product/Index

shoppapp.webui/Views/Product/ProductList.cshtml
@{
    ViewData["Title"] = "List";
}

@model ProductViewModel

@{
    @* Layout = "_Layout"; *@
    var products = Model.Products;
}
@section Categories{
    @await Component.InvokeAsync("Categories")
}
 
        
@if (Model.Products.Count == 0)
{
    @await Html.PartialAsync("_noproduct")
}
else
{
    <div class="row">

        @foreach (var item in products) 
        {
            <div class="col-md-4">
                @await Html.PartialAsync("_product",item)
            </div>
        }
    </div>
} 

shoppapp.webui/Views/Shared/Components/Categories/Default.cshtml
@model List<CategoryEntity>
<div class="list-group">

    <a href="/product/ProductList" class="list-group-item list-group-item-action ">Tüm Kategoriler</a>
    @foreach (var item in Model)
    {
        <a href="/product/ProductList/@item.CategoryId"
            class="list-group-item list-group-item-action @(ViewBag.SelectedCategory == item.CategoryId.ToString()?"active":"")">@item.Name</a>
    }
</div>

shoppapp.webui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="/node/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"  crossorigin="anonymous">
</head>

<body>
    @if (IsSectionDefined("MessageBox"))
    {
        @RenderSection("MessageBox")
    }
    else
    {
        <div class="alert alert-success text-center m-0">
            Genel mesaj
        </div>
    }
    @await Html.PartialAsync("_navbar")
    @* @await Html.PartialAsync("_header") *@

    @RenderSection("Header",false)

    <main class="my-3">
        <div class="container">
            @if (IsSectionDefined("Categories"))
            {
                <div class="row">
                    <div class="col-md-3">
                        @RenderSection("Categories",false)
                    </div>
                    <div class="col-md-9">
                        @RenderBody()
                    </div>
                </div>
            }
            else
            {
                <div class="row">
                    <div class="col-md-12">
                        @RenderBody()
                    </div>
                </div>
            }

        </div>
    </main>

    <footer class="py-5 bg-dark text-white text-center">
        Shopp App | 2021
    </footer>


    @RenderSection("Scripts",false)
</body>

</html>

shoppapp.webui/Views/Shared/_categories.cshtml
@model List<CategoryEntity>
<div class="list-group">
    @foreach (var item in Model)// Model List<CategoryEntity>'yi temsil ediyor
    {
        <a href="#" class="list-group-item list-group-item-action">@item.Name</a>
    }
</div>

shoppapp.webui/Views/Shared/_header.cshtml
 <header>
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4">Shop App</h1>
                <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente sit officia officiis
                    repudiandae necessitatibus labore cupiditate, expedita consequatur nam eveniet dolorem doloribus
                    nihil tempora delectus soluta eum quidem veritatis magni?</p>

            </div>
        </div>
    </header>

shoppapp.webui/Views/Shared/_navbar.cshtml
 <div class="navbar bg-primary navbar-dark navbar-expand-sm">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="/product/productlist" class="nav-link">Products</a>
            </li>
            <li class="nav-item">
                <a href="/product/create" class="nav-link">Add Product</a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">Link 3</a>
            </li>
        </ul>

        <form action="product/productlist" class="form-inline">
            <input name="q" type="text" class="form-control mr-2" placeholder="Search">
            <button type="submit" class="btn btn-outline-light mr-0">Search</button>
        </form>
    </div>

shoppapp.webui/Views/Shared/_noproduct.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-danger">
            Ürün kaydı bulunmamaktadır.
        </div>
    </div>
</div>

shoppapp.webui/Views/Shared/_product.cshtml
@model ProductEntity

<div class="card mb-2">
    <img class="card-img-top"
        src="~/images/@Model.ImageUrl" 
        alt="">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text">@Model.Description</p>
        <a href="/product/Detail/@Model.ProductId" class="btn btn-primary btn-sm">İncele</a>
        <a asp-controller="Product" asp-action="Edit" asp-route-id="@Model.ProductId" class="btn btn-primary btn-sm">Düzenle</a>
        
        <form method="POST" action="/product/delete" style="display: inline;">
            <input type="hidden" name="ProductId" value="@Model.ProductId">
            <button type="submit" class="btn btn-danger btn-sm">Sil</button>
        </form>
    </div>
</div>